### ISSUE TITLE
Model Transferability Test

### ISSUE THREAD

**Issue by Jillian555** [WxxShirley/KDD2024ProCom#1]
Table 5 shows the transferability test of the method. When loading the pre-trained model, how to align the feature dimensions of the source domain and the target domain, for example, the feature dimension of the pretrain dataset is 10, and the feature dimension of the target dataset is 13.

**Comment by WxxShirley** [comment]
Sorry for late reply. 

To ensure transferability, we maintain a consistent input dimension by uniformly setting the input features based on their **structural patterns** (lines 35-57 in `code/data.py`). This enables that each node from any dataset has a consistent input dimension of 5. 
In our main experiments, even with attributed graphs like Twitter and Facebook, we utilize their structural features instead of the original features.

If you have any further questions, feel free to discuss!
